apiVersion: v1
kind: Pod
metadata:
  name: example-1
spec:
  containers:
  - name: app
    image: nginx:latest
    resources:
      requests:
        memory: "1Gi"
        cpu: "3000m"
      limits:
        memory: "2Gi"
        cpu: "4000m"
---
apiVersion: v1
kind: Pod
metadata:
  name: example-2
spec:
  containers:
  - name: app
    image: nginx:latest
    resources:
      requests:
        memory: "1024Mi"
        cpu: "3000m"
      limits:
        memory: "2048Mi"
        cpu: "4000m"
---
apiVersion: v1
kind: Pod
metadata:
  name: example-3
spec:
  containers:
  - name: app
    image: nginx:latest
    resources:
      requests:
        memory: "1048576Ki"
        cpu: "3000m"
      limits:
        memory: "2097152Ki"
        cpu: "4000m"
